# Generated by Django 3.2.7 on 2022-03-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacaoDePerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produtor', models.CharField(max_length=255)),
                ('email_do_produtor', models.CharField(max_length=255)),
                ('cpf_do_produtor', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tipo_de_lavoura', models.CharField(max_length=255)),
                ('data_da_colheita', models.DateField(max_length=255)),
                ('evento', models.CharField(max_length=255)),
            ],
        ),
    ]
